language: node_js
node_js:
  - "6"
env:
  - NODE_ENV=test DATABASE_USERNAME_TEST=postgres DATABASE_PASSWORD_TEST='' DATABASE_NAME_TEST=kails_test DATABASE_HOST_TEST=localhost
services:
  - postgresql
  - redis-server
install:
  - npm install
before_script:
  - psql -c 'create database kails_test;' -U postgres
script:
  - npm run lint
  - npm test
